### ISSUE TITLE
Cannot download data base when installing DBASE_Det_SQLDDDB

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/docker-images#4]
`DBASE_Det_SQLDDDB` provides info for LHCb data processing. Currently, the newer version `v7r11` requires the following way to install:

```
RUN . /opt/lhcb/LbLogin.sh && \
    lbinstall --root=/opt/lhcb reinstall DBASE_Det_SQLDDDB_v7r11
```

Otherwise the installation script would error out. Still, I got the following error:
```INFO: (Update) Updating SQLDDDB database files ...
ERROR: (CondDB_CheckoutSQLite) Failed to download 'repository' file with error: 'HTTP Error 404: Not Found'. Checkout didn't start.
INFO: (Update) The update of SQLDDDB database files has failed.
INFO: (Update) Updating SQLDDDB_Upgrade database files ...
ERROR: (CondDB_CheckoutSQLite) Failed to download 'repository' file with error: 'HTTP Error 404: Not Found'. Checkout didn't start.
INFO: (Update) The update of SQLDDDB Upgrade database files has failed.
```

This indicates that the actual database is not downloaded.

**Comment by yipengsun** [comment]
I've tried to install this package on a lxplus CentOS 7 node, and had exactly the same error message.

I've reported this upstream.

**Comment by yipengsun** [comment]
According to the expert, the newer DaVinci no longer needs this database. Maybe it's time to update DaVinci.

**Comment by yipengsun** [comment]
I tried to install DaVinci v44r8, and still have the same error message:
```
Sorry.. There is no such file or IO problem has been met.                                                            
You were using: ../doc/release_notes.xml
Please check the path to 'release_notes.xml' or just try again later.                                                
Traceback (most recent call last):
  File "/opt/lhcb/lhcb/GAUDI/GAUDI_v29r4/InstallArea/x86_64-centos7-gcc62-opt/scripts/gaudirun.py", line 457, in <module>
    applyConfigurableUsers()
  File "/workspace/build/GAUDI/GAUDI_v29r4/InstallArea/x86_64-centos7-gcc62-opt/python/GaudiKernel/Configurable.py", line 1552, in applyConfigurableUsers_old
  File "/workspace/build/LHCB/LHCB_v44r4/InstallArea/x86_64-centos7-gcc62-opt/python/DetCond/Configuration.py", line 513, in __apply_configuration__
TypeError: 'int' object has no attribute '__getitem__'
```

**Comment by yipengsun** [comment]
On `lxplus`, I can only find these `release_notes.xml`:
```
./lhcb/SQLite/SQLDDDB/doc/release_notes.xml
./lhcb/SQLite/SQLDDDB_Upgrade/doc/release_notes.xml
```

**Comment by yipengsun** [comment]
The latest `DBASE_Det_SQLDDDB` can download the database successfully:
```WARNING : 3 RPM files to install
WARNING : Installing /tmp/lbinstall-tmp/DBASE_Det_SQLDDDB_v7r12-1.0.0-1.noarch.rpm just-db=False
WARNING : Setting RPM_INSTALL_PREFIX to /opt/lhcb
Creating link in update.d
mkdir: created directory '/opt/lhcb/etc/update.d'
Running Update script
SQLite/
SQLite/SQLDDDB/
SQLite/SQLDDDB/db/
SQLite/SQLDDDB/db/DDDB_upgrade.db
SQLite/SQLDDDB/db/dddb_mapmt_upgrade_20110519.db
SQLite/SQLDDDB/db/dddb_simcond_mapmt_upgrade_20111202.db
SQLite/SQLDDDB/db/ONLINE-2010.db
SQLite/SQLDDDB/db/ONLINE-2012.db
SQLite/SQLDDDB/db/ONLINE-2011.db
SQLite/SQLDDDB/db/ONLINE-2013.db
SQLite/SQLDDDB/db/ONLINE-2008.db
SQLite/SQLDDDB/db/ONLINE-2009.db
SQLite/SQLDDDB/db/ONLINE-2014.db
SQLite/SQLDDDB/db/CALIBOFF.db
SQLite/SQLDDDB/db/ONLINE-2015.db
SQLite/SQLDDDB/db/ONLINE-2016.db
SQLite/SQLDDDB/db/DQFLAGS.db
SQLite/SQLDDDB/db/DDDB.db
SQLite/SQLDDDB/db/ONLINE-2017.db
SQLite/SQLDDDB/db/LHCBCOND.db
SQLite/SQLDDDB/db/SIMCOND.db
SQLite/SQLDDDB/db/ONLINE-2018.db
SQLite/SQLDDDB/doc/
SQLite/SQLDDDB/doc/release_notes.xsd
SQLite/SQLDDDB/doc/release_notes.xsl
SQLite/SQLDDDB/doc/release_notes.xml
SQLite/SQLDDDB/catalog
SQLite/SQLDDDB_Upgrade/
SQLite/SQLDDDB_Upgrade/db/
SQLite/SQLDDDB_Upgrade/db/SIMCOND.db
SQLite/SQLDDDB_Upgrade/db/DDDB.db
SQLite/SQLDDDB_Upgrade/doc/
SQLite/SQLDDDB_Upgrade/doc/release_notes.xsd
SQLite/SQLDDDB_Upgrade/doc/release_notes.xsl
SQLite/SQLDDDB_Upgrade/doc/release_notes.xml
SQLite/SQLDDDB_Upgrade/catalog
```

But `DaVinci/v45r3` still complains:
```
# WARNING: file '/opt/lhcb/lhcb/DBASE/TCK/L0TCK/v5r32/options/L0DUConfig.opts' already included, ignored.
# WARNING: something else configured a decoder already, Raw/Spd/Digits CaloDigitsFromRaw/SpdFromRaw
# WARNING: something else configured a decoder already, Trig/L0/Calo L0CaloCandidatesFromRaw/L0CaloFromRaw
# WARNING: something else configured a decoder already, Trig/L0/FullCalo L0CaloCandidatesFromRaw/L0CaloFromRaw
# WARNING: something else configured a decoder already, Trig/L0/L0DUReport L0DUFromRawAlg/L0DUFromRaw
# WARNING: something else configured a decoder already, Raw/Prs/Digits CaloDigitsFromRaw/PrsFromRaw
# WARNING: something else configured a decoder already, Raw/Ecal/Digits CaloZSupAlg/EcalZSup
# WARNING: something else configured a decoder already, Raw/Hcal/Digits CaloZSupAlg/HcalZSup
# WARNING: something else configured a decoder already, Trig/L0/MuonCtrl L0MuonCandidatesFromRaw/L0MuonFromRaw
# WARNING: something else configured a decoder already, Trig/L0/MuonBCSU L0MuonCandidatesFromRaw/L0MuonFromRaw
# WARNING: something else configured a decoder already, Trig/L0/MuonData L0MuonCandidatesFromRaw/L0MuonFromRaw
# WARNING: Using default tag <latest:2012> for partition DQFLAGS
# WARNING: Property 'DataType' is set in both 'DigiConf' and 'SimConf', using 'DigiConf.DataType'
# No Writer defined for DIGI
Traceback (most recent call last):
  File "/opt/lhcb/lhcb/GAUDI/GAUDI_v32r2/InstallArea/x86_64-centos7-gcc8-opt/scripts/gaudirun.py", line 540, in <module>
    applyConfigurableUsers()
  File "/workspace/build/GAUDI/GAUDI_v32r2/InstallArea/x86_64-centos7-gcc8-opt/python/GaudiKernel/Configurable.py", line 1640, in applyConfigurableUsers_old
  File "/workspace/build/LHCB/LHCB_v45r2/InstallArea/x86_64-centos7-gcc8-opt/python/DetCond/Configuration.py", line 210, in __apply_configuration__
  File "/workspace/build/LHCB/LHCB_v45r2/InstallArea/x86_64-centos7-gcc8-opt/python/DetCond/Configuration.py", line 147, in _getLatestTag
ValueError: CondDB._getLatestTag: ToolSvc.GitDQFLAGS: missing repository path
```

**Comment by yipengsun** [comment]
Fixed. We have to manually mirror, **not clone** the LHCb database to `/opt/lhcb/lhcb/git-conddb` folder, and install some missing dependencies.
