### ISSUE TITLE
Update DaVinci docker and include RelatedInfoTools for HLT1 emulation

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/docker-images#8]
We should use this chance to update to latest version of `DaVinci/v45`: `DaVinci/v45r6`.

Also, as Simone suggested, we need to include RelatedInfoTools for additional branches that will be processed by some scripts offline.

- RelatedInfoTools: https://gitlab.cern.ch/lhcb-slb/B02DplusTauNu/-/tree/master/tuple_production/tuple_tools_src/RelatedInfoTools
- Sample DaVinci script: https://gitlab.cern.ch/lhcb-slb/B02DplusTauNu/-/blob/master/tuple_production/B2Dmu_AllSpecies_MC2016.py
- Offline processing script:  https://gitlab.cern.ch/lhcb-slb/B02DplusTauNu/tree/master/tuple_processing_chain

Note that the RelatedInfoTools might not be updated.

**Comment by yipengsun** [comment]
Block umd-lhcb/lhcb-ntuples-gen#59.

**Comment by yipengsun** [comment]
To be precise, this is the error message:
```
# --> Including file '/data/run1-rdx/conds/cond-std-2012.py'
# WARNING: : Module DDDB.Configuration not found (needed for configurable DDDBConf)
# WARNING: : Module GaudiConf.DstConf not found (needed for configurable DstConf)
# WARNING: : Module L0DU.Configuration not found (needed for configurable L0Conf)
# WARNING: : Module GaudiConf.TurboConf not found (needed for configurable TurboConf)
# WARNING: : Module GaudiConf.DstConf not found (needed for configurable DstConf)
Traceback (most recent call last):
  File "/opt/lhcb/lhcb/GAUDI/GAUDI_v34r1/InstallArea/x86_64-centos7-gcc9-opt/scripts/gaudirun.py", line 547, in <module>
    exec(o, g, l)
  File "<string>", line 1, in <module>
  File "/workspace/build/GAUDI/GAUDI_v34r1/InstallArea/x86_64-centos7-gcc9-opt/python/GaudiKernel/ProcessJobOptions.py", line 502, in importOptions
  File "/workspace/build/GAUDI/GAUDI_v34r1/InstallArea/x86_64-centos7-gcc9-opt/python/GaudiKernel/ProcessJobOptions.py", line 470, in _import_python
  File "/data/run1-rdx/conds/cond-std-2012.py", line 3, in <module>
    DaVinci().DataType = '2012'
  File "/workspace/build/GAUDI/GAUDI_v34r1/InstallArea/x86_64-centos7-gcc9-opt/python/GaudiKernel/ConfigurableMeta.py", line 85, in __call__
  File "/workspace/build/GAUDI/GAUDI_v34r1/InstallArea/x86_64-centos7-gcc9-opt/python/GaudiKernel/Configurable.py", line 282, in __new__
  File "/workspace/build/LHCB/LHCB_v45r5/InstallArea/x86_64-centos7-gcc9-opt/python/LHCbKernel/Configuration.py", line 36, in __init__
  File "/workspace/build/GAUDI/GAUDI_v34r1/InstallArea/x86_64-centos7-gcc9-opt/python/GaudiKernel/Configurable.py", line 1346, in __init__
  File "/workspace/build/GAUDI/GAUDI_v34r1/InstallArea/x86_64-centos7-gcc9-opt/python/GaudiKernel/ConfigurableMeta.py", line 85, in __call__
  File "/workspace/build/GAUDI/GAUDI_v34r1/InstallArea/x86_64-centos7-gcc9-opt/python/GaudiKernel/Configurable.py", line 282, in __new__
  File "/workspace/build/LHCB/LHCB_v45r5/InstallArea/x86_64-centos7-gcc9-opt/python/LHCbKernel/Configuration.py", line 36, in __init__
  File "/workspace/build/GAUDI/GAUDI_v34r1/InstallArea/x86_64-centos7-gcc9-opt/python/GaudiKernel/Configurable.py", line 1346, in __init__
TypeError: 'NoneType' object is not callable
```

**Comment by yipengsun** [comment]
In `DaVinci/v45r4`, these names seem to be defined in:
```
LHCB/LHCB_v45r3/InstallArea/x86_64-centos7-gcc9-opt/lib/LHCb.confdb
```

**Comment by yipengsun** [comment]
For `DaVinci/v45r6`, the same file exists as well.

**Comment by yipengsun** [comment]
It turns out that for our `DaVinci/v45r6` docker image, the actual `DDDB.Configuration.py` exists in:
```
/opt/lhcb/lhcb/LHCB/LHCB_v45r5/InstallArea/x86_64-centos7-gcc9-opt/python/DDDB
```

Don't know why it is not picked up by `DaVinci`.

**Comment by yipengsun** [comment]
When I tried to import `DDDB.Configuration` in a `python2` inside `lb-run DaVinci/v45r6 bash`, I got the following error:
```
>>> import DDDB.Configuration
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/build/LHCB/LHCB_v45r5/InstallArea/x86_64-centos7-gcc9-opt/python/DDDB/Configuration.py", line 15, in <module>
ImportError: No module named builtins
```

**Comment by yipengsun** [comment]
Installing `future` solved that problem. Now I'm getting:
```
/opt/lhcb/lhcb/GAUDI/GAUDI_v34r1/InstallArea/x86_64-centos7-gcc9-opt/include/GaudiKernel/EventContext.h:15:10: fatal error #include <any>
```

**Comment by yipengsun** [comment]
The latest DaVinci setup procedure has been confirmed to working in both docker and lxplus.
